mapfile.csv
Add MTL device ID 0xAC to match [1].
[1] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/arch/x86/include/asm/intel-family.h?id=5515d21c6817bc27b0b13c61edf22b09b58bc647
=> mapfile: Update MTL entries

mapfile.csv
The `mapfile.csv` Version column primarily uses capital V. This commit fixes a few of my previous updates which introduced lower case v.
=> mapfile: Replace v1 with V1

.github/workflows/create-perf-json.yml, .gitignore
The goal of this PR is to introduce a simple GitHub action to run and check `create_perf_json.py`. With potentially ongoing JSON refactoring I want to make sure this script continues to function. As a somewhat related change, `scripts/perf` is added to `.gitignore` since it is an output directory.
1. Pushes.
2. Pull requests.
3. Fixed schedule for once a week.
The default output directory `scripts/perf` for 10 days.
=> CI: Add GitHub Action for create_perf_json.py

scripts/create_perf_json.py, scripts/metric.py, scripts/unittesting/metric_test.py
The metric framework turns a string metric into a tree. This is used to rewrite metrics in a list into using each other as terms. By adding in the simpler CORE_CLKS (without #EBS_Mode) then CORE_CLKS is substituted in, while the actual CORE_CLKS keeps to use #EBS_Mode. This works around Valkyrie metrics being generated from converted TMA metrics with #EBS_Mode removed.
=> Metric framework and #EBS_Mode fix for Valkyrie metrics

scripts/create_perf_json.py, scripts/metric.py
A collection of create_perf_json fixes.
Perf metrics are case insensitive but we may have multiple metrics during parsing with different capitalizations. If this happens we may end up making the metric recursive with itself. Avoid this by making the rewrite test case insensitive.
Avoid string based substitution of "if" expressions, use the metric approach that doesn't break parentheses.
Add extra debug logging if parsing a metric yields a syntax error.
=> Fixes for create_perf_json.py

README.md
This PR primarily adds uncore experimental to event file type descriptions. Other minor updates address spelling changes and cleanup stale information. Fixes https://github.com/intel/perfmon/issues/46.
=> README: Document uncore_experimental

README.md
This PR creates top level headers for How to Contribute and Support. Existing text for Perfmon metrics and events are moved to the corresponding new section. A summary outline linking to each of the main readme headers is also added.
=> readme: Update contribution and support sections

mapfile.csv
Add `0xCF` to support Linux enabling. Emerald Rapids device ID referenced from [1].
[1] https://lore.kernel.org/all/20221103203310.5058-1-tony.luck@intel.com/
=> mapfile: Add EMR

scripts/create_perf_json.py, scripts/metric.py
A collection of updates:
- rename TMA's Info metrics to match the Valkyrie Into metric names (ie tma_info_...).
- add support for Locate-with to Valkyrie metrics.
- add event grouping flags, so that events for metrics aren't grouped if the group won't count in that scenario. The flag names need an updated Linux perf. The groupings were computed manually based on SNB, SKL or ICL style groupings.
- generate the 'Threshold' column as a boolean metric that combines parent and other values as specified. This value is also copied to Valkyrie metrics.
Adding the threshold is a precursor to removing hard coded metrics out of the Linux perf code. The hard coded metrics use duplicate aggregation logic which was the cause of a double counting regression. Everything else is either Valkyrie alignment …
=> Improvements to create_perf_json.py

README.md
* Insert a new link for event documentation in HTML form https://perfmon-events.intel.com.
* Update the Platform Monitoring link since it was not valid. The Internet Archive's last relevant snapshot was in 2014 https://web.archive.org/web/20130709032053/http://software.intel.com/en-us/platform-monitoring. Later crawls were redirected to https://www.intel.com/content/www/us/en/developer/topic-technology/platform-analysis-technology/overview.html.
* Update link for monitoring integrated memory controller requests. The Internet Archive's last snapshot for the prior URL was in 2018 https://web.archive.org/web/20181106212644/http://software.intel.com/en-us/articles/monitoring-integrated-memory-controller-requests-in-the-2nd-3rd-and-4th-generation-intel.
* Replace …
=> readme: Update additional information and errata links

.github/CODEOWNERS, .gitignore
This commit introduces GitHub's CODEOWNERS file to automatically add reviewers to pull requests. Listed owners are a starting point for reviews, or to add other contacts to the pull request.
Gitignore is also updated to add Python's `__pycache__`.
=> Introduce CODEOWNERS

scripts/create_perf_json.py
Correctly rename certain PMUs.
Give every uncore PMU a topic, fail if the PMU is unknown.
Avoid the generation of trigraphs (??) that can cause C compiler warnings and failures.
=> Uncore PMU fixes

scripts/create_perf_json.py
Upstream Linux perf now supports grouping topdown events even without groups so remove TODO.
=> Allow constraints on Icelake+ topdown metrics

.github/CODEOWNERS
This commit splits the ownership/notifications into two groups. One for create_perf_json.py and associated files. One for perf_format_converter.py and associated files.
=> codeowners: Update contacts for scripting

scripts/create_perf_json.py
Models without perf metric events may lead to inaccuracies when run with a single benchmark. Add a new metric group 'Default' to be used in place of 'TopdownL1' and 'TopdownL2' by perf when adding default metrics.
Currently, only the platforms which support the performance metric feature (big core after ICL) have the 'Default' group. E-core doesn't support the feature. So they are not marked as Default. 
Add DefaultMetricgroupName so perf can understand the real metric group when using the default mode.
Avoiding grouping events for the default mode as well.
=> Add Default metric group for models with perf metric events

scripts/create_perf_json.py
Update the grouping constraints for Icelake. The previous groups missed certain cases due to erroneous event grouping.
=> Update icelake+ metric constraints

scripts/create_perf_json.py
uncore_arb on Skylake has no thresh format, it should use cmask. This confusion creeps in because on SkylakeX uncore_cha is used instead of uncore_arb, uncore_cha having a thresh format.
=> Fix format used for Skylake UNC_ARB_TRK_OCCUPANCY.DATA_READ:c1

.github/dependabot.yml, .github/workflows/check-markdown-links.yml
* Dependabot
* Introduce `dependabot.yml` to enable version updates for pip and GitHub Actions. Dependabot scanning and alerts for dependencies with security updates is already enabled. 
* At the moment Python scripts aren't using additional packages via `requirements.txt`. Enabling PIP scans is for upcoming tools / checks.
* Limit link checks to `intel/perfmon`
* Automatically checking links is intended to be a low volume reminder to update stale links. It isn't necessary for every fork (examples below) to also act as a reminder. This pull request checks if the repository is `intel/perfmon` and further removes `push` and `pull_request`  triggers.
* https://github.com/edwarddavidbaker/perfmon/actions/workflows/check-markdown-links.yml?query=event%3Aschedule
* …
=> CI Updates: Add dependabot.yml and limit link checks to intel/perfmon

scripts/create_perf_json.py
Broadwell-de follows broadwell for core events but broadwellx for uncore. Prior to this patch the uncore_arb PMU was tried to be used, however, it isn't present and uncore_cbox should be used. Rework how this is done in the code, in find_form for Page_Walks_Utilization force the BDX lookup. For lookups that result in UNC_ARB retry the lookup using BDX as lookup order.
Note, this only changes the metric tma_info_system_dram_bw_use as:
-        "MetricExpr": "64 * (arb@event\\=0x81\\,umask\\=0x1@ + arb@event\\=0x84\\,umask\\=0x1@) / 1e6 / duration_time / 1e3",
+        "MetricExpr": "64 * (UNC_M_CAS_COUNT.RD + UNC_M_CAS_COUNT.WR) / 1e9 / duration_time",
=> Rework broadwell-de conversion

scripts/create_perf_json.py
The el-start event is from sysfs (not json) and isn't present on SPR. The tsx_cycles_per_elision metric uses the event so remove the metric on SPR. Switch from using cycles-t as the sysfs event indicator the metric will work to el-start in case HLE gets disabled but not TSX.
=> Remove tsx_cycles_per_elision metric from SPR

.github/workflows/create-perf-json.yml, scripts/create_perf_json.py
Previously event files were hosted at https://download.01.org/perfmon and fetching them with `urllib` was necessary. After migrating to GitHub we no longer need to fetch files using `urllib`.
* Script arguments
* Removed base path argument. At this point in time, `create_perf_json.py` only operates on files in this repository.
* Add Path type to argument parser.
* Migrate to Path
* Use `pathlib.Path` to construct file and folder paths.
* Updated type annotations with Path.
* Replaced `urlopen()` with `open()`.
* Removed unused imports `os` and `urllib`.
* Switched a few `try:` blocks to `if <path>.is_file()`.
* CI
* Execute `metric` tests.
=> create_perf_json: Migrate to pathlib.Path for file operations

scripts/create_perf_json.py
ADL/RKL were specifying a CPU PMU for uncore events.
UNCORE_FREQ was missing a unit and failing on ADL.
Compatibility issues for future TMA metrics.
=> Fix perf tool json conversion issues

.github/workflows/check-markdown-links.yml, README.md
* Set `check-markdown-links.yml` permissions to `contents: read`. This action does not need additional read or write permissions.
| Action | Section | Link | Notes |
| --- | --- | --- | --- |
| Added | MTL Errata | [Document 792254](https://cdrdv2.intel.com/v1/dl/getContent/792254?explicitVersion=true) | |
| Removed | HSW Errata | [4th-gen-core-family-desktop-specification-update.pdf](https://www.intel.com/content/dam/www/public/us/en/documents/specification-updates/4th-gen-core-family-desktop-specification-update.pdf) | For historical reference The Wayback Machine captured a [snapshot in September of 2023](https://web.archive.org/web/20230906125433/https://www.intel.com/content/dam/www/public/us/en/documents/specification-updates/4th-gen-core-family-desktop-specification-update.pdf).|
| …
=> Update link checks

.github/workflows/check-markdown-links.yml, .github/workflows/create-perf-json.yml
Instead of referencing versions, the guidance is to pin actions to a full length SHA corresponding to the release tag [1] [2]. Dependabot will continue to automatically monitor and open PRs for versions [3].
| Action                            | Old | New                    |
| --- | --- | --- |
| checkout                          | v4  | v4.1.1 release commit  |
| github-action-markdown-link-check | v1  | v1.0.15 release commit |
| setup-python                      | v5  | v5.0.0 release commit  |
| upload-artifact                   | v4  | v4.3.0 release commit  |
[1] https://securityscorecards.dev/viewer/?uri=github.com/intel/perfmon
[2] https://github.com/ossf/scorecard/blob/497b851040f18b6cacfbc67500b6fad98ac5e367/docs/checks.md#pinned-dependencies
[3] …
=> ci: Pin GitHub Actions

scripts/perf_format_converter.py
Restrict character range from A-z to A-Z. Characters such as [ are not valid matches. [Identified by CodeQL](https://github.com/intel/perfmon/security/code-scanning/1).
Examples of events passed into `translate_event_options()` before they are split on `:`.
```
UNC_C_TOR_INSERTS.OPCODE:opc=0x1c8:tid=0x3e
UOPS_ISSUED.ANY:c1
OFFCORE_REQUESTS_OUTSTANDING.DEMAND_DATA_RD:u0x10
UOPS_EXECUTED.CORE:i1:c1
```
=> perf_format_converter: Refine event options expression

.github/workflows/scorecard.yml
This commit introduces the Open Source Security Foundation (OpenSSF) Scorecard GitHub Action [1](https://securityscorecards.dev/), [2](https://github.com/ossf/scorecard-action#installation). The dashboard for this project is located at [3](https://securityscorecards.dev/viewer/?uri=github.com/intel/perfmon). The overall goal is to actively publish score card results instead of passively depending on an external scan cadence.
=> ci: Add OpenSSF Scorecard GitHub Action

scripts/create_perf_json.py, scripts/metric.py, scripts/perf_format_converter.py, scripts/unittesting/metric_test.py, scripts/unittesting/test_perf_format_converter.py
This pull request updates `scripts` headers. No license changes. Continues as BSD-3-Clause.
1. Add `SPDX-License-Identifier: BSD-3-Clause` if no license was present.
2. Use `SPDX-License-Identifier: BSD-3-Clause` in place of full license to standardize Python scripts. Full license text is located at https://github.com/intel/perfmon/blob/main/LICENSE .
3. Add `Copyright (C) ...` entries for all Python scripts.
4. Update Copyright notices based on contribution history.
=> scripts: Update license and copyright

scripts/create_perf_json.py
Sometimes we might want to only update and regenerate event files, so add a command option to skip the metric file processing and generate step. 
When we do event grouping base on hardware counter information, we need to know the list of counters an event could be collected on and also how many counters available on each Perfmon unit. Therefore, add several attributes and function to generate this type of info. This change will create a new file named `counter.json` locate together with all the event json files that includes Perfmon unit name and number of counters. 
A simple example of content in `counter.json`:
```
{
{  
"Unit": "core",
"NumFixedCounters": "4",
"NumCounters": "8"
},
{
"Unit": "PCU",
"NumFixedCounters": "0",
"NumCounters": "4"
},
{
"Unit": "IRP",
"NumFixedCounters": "0", …
```
=> For perf converter, add some new fields for event grouping

.github/workflows/create-perf-json.yml, scripts/create_perf_json.py, scripts/unittesting/test_create_perf_json.py
The primary goal of this commit is to address an inefficient regex identified by CodeQL https://github.com/intel/perfmon/security/code-scanning/6. The goal of the `MIN_MAX_PEBS` expression is to extract groups for the leading event name, `$PEBS` in the first function argument, and the alternative function argument. The following are example formula snippets.
```
MEM_INST_RETIRED.STLB_HIT_LOADS*min($PEBS, 7)
cpu_core@MEM_LOAD_L3_HIT_RETIRED.XSNP_MISS@*min($PEBS, 24 * tma_info_system_core_frequency)
MEM_INST_RETIRED.SPLIT_LOADS*min($PEBS, tma_info_memory_load_miss_real_latency)
```
`$PEBS` is replaced with the event name and a trailing `:R` or `R`.
```
Input:  EVENT.A*min($PEBS, 4)
Output: EVENT.A * min(EVENT.A:R, 4)
```
```
Input:  cpu_core@EVENT.B@*min($PEBS, 24 * …
```
=> create_perf_json: Fix inefficient regex warning

.github/bandit.yml, .github/workflows/bandit.yml, .gitignore, requirements.txt
This commit introduces automated Bandit scans. Bandit compliments the existing CodeQL scanning information and is recommended per Intel development policies. This commit does not address issues identified by Bandit. They will be resolved in subsequent pull requests.
* Exclusions / Skips 
* Unittests in `scripts/unittesting` are excluded.
* B101 which checks for `assert` is ignored.
=> ci: Introduce Bandit scans

scripts/create_perf_json.py
The PMU uncore_clock isn't present on Skylake and earlier machines. The event is present on cbox_0 (note, the suffix is included to avoid multiple cbox PMUs being added together).
Note, are the event encodings for BDW/HDW/SKL cbox_0 correct in this context? The json shows:
"EventCode": "0x0",
"UMask": "0x01",
but this maybe should be "event=0xff,umask=0x00". As uncore_clock isn't present on these models perf currently doesn't report this event.
=> Fix PMU for UNC_CLOCK.SOCKET on BDW, HSW, SKL

scripts/create_perf_json.py
The metrics tma_few_uops_instructions and tma_microcode_sequencer require all 6 counters, therefore the metric can't succeed if the NMI watchdog is enabled. Update the constraints so that if the NMI watchdog is enabled the events won't be grouped.
=> Fix tma_heavy_operations_group for Skylake

scripts/create_perf_json.py, scripts/perf/alderlake/adl-metrics.json, scripts/perf/cascadelakex/clx-metrics.json, scripts/perf/meteorlake/mtl-metrics.json, scripts/perf/skylake/skl-metrics.json, scripts/perf/skylakex/skx-metrics.json
Changes:
1. Update for [ PR#178](https://github.com/intel/perfmon/pull/178#issue-2286076036) "Fix tma_heavy_operations_group for Skylake"
2. Update string match for pmu_prefix on hybrid platforms.
=> Perf converted json etma3.6 updates

scripts/create_perf_json.py
This pull request primarily resolves the following warnings. Python 3.12 (default in Ubuntu 24.04) raises warnings for invalid escape sequences. They are also present in CI jobs https://github.com/intel/perfmon/actions/runs/9568397876/job/26378512313#step:5:12 .
```
./create_perf_json.py:290: SyntaxWarning: invalid escape sequence '\?'
result = re.sub('\?\?\?', '?', result)
./create_perf_json.py:614: SyntaxWarning: invalid escape sequence '\-'
cycles_in_tx = metric.Event('cycles\-t')
./create_perf_json.py:615: SyntaxWarning: invalid escape sequence '\-'
transaction_start = metric.Event('tx\-start')
./create_perf_json.py:616: SyntaxWarning: invalid escape sequence '\-'
cycles_in_tx_cp = metric.Event('cycles\-ct')
./create_perf_json.py:635: SyntaxWarning: invalid escape sequence '\-' …
```
=> create_perf_json: Specify raw strings and make the script directly executable

README.md
Update `README.md` to include additional notes regarding the availability of `CounterHTOff`. This attribute is not published on ICL, ICX, and subsequent platforms. To review a live version of these markdown changes refer to https://github.com/edwarddavidbaker/perfmon/tree/readme-counterhtoff?tab=readme-ov-file#counterhtoff .
* Updated `CounterHTOff` documentation section.
* Replaced `Intel&copy;` with `Intel&reg;`. Also replaced one instance of `(R)` with the HTML entity.
* Replaced tabs with spaces and removed trailing spaces.
=> readme: Add CounterHTOff notice, update HTML entities, fixup spaces

requirements.txt, scripts/ci/verify_mapfile/requirements.txt, scripts/metric.py
* Bandit is flagging eval() as a possible issue [#7](https://github.com/intel/perfmon/security/code-scanning/7) . In this instance, usage is already ignored for pylint.
* Automated scanning recommends pinning requirements.txt packages to a specific version https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies .
=> ci: Bandit updates

mapfile.csv, scripts/ci/verify_mapfile/mapfile_schema.json, scripts/ci/verify_mapfile/verify_mapfile.py, scripts/create_perf_json.py
This commit adds ARL-H model ID 0xC5 (https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/arch/x86/include/asm/intel-family.h) to `mapfile.csv`. Crestmont event content and updates were merged in https://github.com/intel/perfmon/pull/229 .
=> mapfile: Add ARL-H

scripts/create_perf_json.py
GitHub actions running `create_perf_json.py` are currently failing. This commit is a quick follow-up to metrics added in https://github.com/intel/perfmon/pull/250 . Ignores handle equations such as the following.
```
cbox_0@event\=0x0@
cha_0@event\=0x0@
imc_0@event\=0x0@
pcu_0@UNC_P_CLOCKTICKS@
```
=> create_perf_json: Add pcu_0 to event check ignores

scripts/create_perf_json.py
This commit **unsets** `UMaskExt` for events which also populate `PortMask` or `FCMask`.
=> create_perf_json: Drop UMaskExt depending on FCMask and PortMask

ADL/metrics/perf/alderlake_metrics_goldencove_core_perf.json, ARL/metrics/perf/arrowlake_metrics_lioncove_core_perf.json, LNL/metrics/perf/lunarlake_metrics_lioncove_core_perf.json, MTL/metrics/perf/meteorlake_metrics_redwoodcove_core_perf.json
Replaces instances of "cpu@" with "cpu_core@" on hybrid client platforms.
=> Hybrid metric fix for cpu_core@ string

.github/dependabot.yml
This commit ignores Python and GitHub Action patch updates. Major and minor versions will still trigger an update. Security updates are not changed. It is noisy to update packages for every `patch` in `major.minor.patch`. Focusing on `major` and `minor` will provide sufficient updates for packages used in this project.
* https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#specifying-dependencies-and-versions-to-ignore
=> dependabot: Ignore patch updates

GNR/metrics/perf/graniterapids_metrics_perf.json
Changing GNR C-state metrics to report number of cores rather than percentage.
=> GNR cstate metric update

GNR/metrics/perf/graniterapids_metrics_perf.json
Adding yet another fix for cstate metric.
"UNC_P_CLOCKTICKS[0]" needs to be converted to "pcu_0@UNC_P_CLOCKTICKS@".
=> Fixing cstate metric syntax for perf

scripts/create_perf_json.py
Switch Default TopdownL1 metrics to excluding rather than including models. Add EMR and SPR TopdownL2 metrics to Default group.
=> Update the Default metric groups for newer models

scripts/create_perf_json.py
Include CNCU Unit for event UNC_CLOCK.SOCKET on ARL and MTL
=> Add Unit "CNCU" to UNC_CLOCK.SOCKET for MTL and ARL

scripts/create_perf_json.py
The generic PDIST availability information can only be found in the SDM. Also, some events may not support PDIST. It's hard to find that information either.
Append the PDIST information into the PublicDescription of the event list, if it's available.
If the event or platform doesn't support PDIST, nothing is changed.
The PDIST Counter information may be useful for the hardware-aware grouping of Linux perf. But the hardware-aware grouping only works for perf stat for now. There is no plan to enable the hardware-aware grouping for perf record shortly. Adding a dedicated PDIST field is unnecessary.
=> create_perf_json: Expose PDIST Counter information in PublicDescription

scripts/create_perf_json.py
This small PR resolves the regex library warnings showing starting Python3.11 which you can find in the [CI logs](https://github.com/intel/perfmon/actions/runs/15280186842/job/42976937531#step:5:12):
```python
/home/runner/work/perfmon/perfmon/scripts/create_perf_json.py:1542: DeprecationWarning: 'count' is passed as positional argument
```
=> Resolve regex library deprecation warnings

EMR/metrics/emeraldrapids_metrics.json, EMR/metrics/perf/emeraldrapids_metrics_perf.json, SPR/metrics/perf/sapphirerapids_metrics_perf.json, SPR/metrics/perf/sapphirerapidshbm_metrics_perf.json, SPR/metrics/sapphirerapids_metrics.json, SPR/metrics/sapphirerapidshbm_metrics.json
Removing array notation for UNC_P_CLOCKTICKS references.
=> SPR_EMR_cstate_metric_update
